### ISSUE TITLE
Setting createBTCWallet to false do not allow email validation. Returns stack trace as reponse

### ISSUE THREAD

**Issue by ikamthania** [synereo/gloseval#2]
Steps to reproduce:
1. Use rest client(E.g. Advanced Rest Client plugin for chrome) to register a new user by making a POST call to http://54.201.214.48:9876/api with payload
{"msgType":"createUserRequest","content":{"email":"YOUR EMAIL ADDRESS","password":"s","jsonBlob":{"name":"NAME"},"createBTCWallet":false}}
2. Check mail for the validation code and try verifying the code by making a POST call to http://54.201.214.48:9876/api with payload
{"msgType":"confirmEmailToken","content":{"token":"2d26f030"}}
It returns Internal Server Error as response with complete stack trace similar to attached file.

[arc-response-2016 Jan 6 17-50-55.txt](https://github.com/synereo/gloseval/files/79773/arc-response-2016.Jan.6.17-50-55.txt)

**Comment by edeykholt** [comment]
I think the issue was that the first message had createBTCWallet:false and the second message handler expects a bitcoin address as a parameter in that case.  Nirvanic was able to work around this by updating the first call to createBTCWallet:true.  Still, there is a bug in the server code in handling the confirmEmailToken in that it should not return a stack trace to the API client.
